### ISSUE TITLE
Precipitation amount throwing errors

### ISSUE THREAD

**Issue by andreasm84** [gjohansson-ST/pytrafikverket#61]
Hi.

I recently updated HA core to the most recent one.
Since then the Trafikverket Weather integration has started acting up with errors in the log and a non-functional precipitation measurment.

Log:
`ValueError: Sensor sensor.stugunas_precipitation_intensity has device class 'precipitation_intensity', state class 'measurement' unit 'mm/h' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '0.10.1' (<class 'str'>)`

The actual response(partial) from the API:
`"Precipitation": {
									"Rain": false,
									"Snow": true,
									"TotalWaterEquivalent": {
										"Value": 0.1
									}
								}`

It would seem that the value 0.1 is concatenated on itself to result in the string '0.10.1'.

I believe I have tracked down the problem to this line where the value is interpreted as a string rather than a float, resulting in a string duplication instead of a multiplication:
https://github.com/gjohansson-ST/pytrafikverket/blame/2f577242a810224cc77065d90ac55295194437f5/pytrafikverket/trafikverket_weather.py#L151

I'm not that well versed in python so I hope this guess isn't totally of the mark.

Thank you.

**Comment by gjohansson-ST** [comment]
Excellent investigation. I'll try to make a PR shortly to address the issue. 👍

**Comment by gjohansson-ST** [comment]
Close by #62
